name: Kodi-Addon-Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kodi-addon-checker

    - name: LEIA
      run: kodi-addon-checker --branch leia

    - name: MATRIX
      run: kodi-addon-checker --branch matrix

  deploy:
    name: Deploy Addon
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/Space2Walker/kodi-space-repo/dispatches --data '{"event_type": "build_application"}'
